---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-latest
  image: plugins/docker
  settings:
    auto_tag: true
    password:
      from_secret: docker_password
    registry: registry.huefox.com
    repo: registry.huefox.com/fuzzysearch
    username:
      from_secret: docker_username
  when:
    branch:
    - master

- name: build-branch
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    registry: registry.huefox.com
    repo: registry.huefox.com/fuzzysearch
    tags: ${DRONE_BRANCH}
    username:
      from_secret: docker_username
  when:
    branch:
      exclude:
      - master

...
