---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: rust:1-slim-buster
  commands:
    - apt-get update -y && apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libavdevice-dev pkg-config clang llvm
    - cargo build
    - cargo test

...
