[package]
name = "fuzzysearch"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
pretty_env_logger = "0.4"

tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

opentelemetry = "0.1"
tracing-opentelemetry = "0.1"

tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
futures-util = "0.3"

chrono = "0.4"
bytes = "0.5"

serde = { version = "1", features = ["derive"] }
warp = "0.2"

tokio-postgres = "0.5"
bb8 = "0.4"
bb8-postgres = "0.4"

img_hash = "3"
image = "0.22"
hamming = "0.1"

bk-tree = "0.3"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
