[package]
name = "fuzzysearch"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.3.1"

tokio = { version = "0.2.9", features = ["full"] }
chrono = "0.4.10"
futures = "0.3.1"
futures-util = "0.3.1"
bytes = "0.5.3"

serde = { version = "1.0.104", features = ["derive"] }
warp = { git = "https://github.com/seanmonstar/warp.git" }

tokio-postgres = "0.5.1"
bb8 = { git = "https://github.com/khuey/bb8.git" }
bb8-postgres = { git = "https://github.com/khuey/bb8.git" }

img_hash = "3.0.0"
image = "0.22"
hamming = "0.1.3"
