[package]
name = "fuzzysearch"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

opentelemetry = "0.6"
opentelemetry-jaeger = "0.5"
tracing-opentelemetry = "0.5"

tokio = { version = "0.3", features = ["macros", "rt-multi-thread", "sync"] }
futures = "0.3"
futures-util = "0.3"

chrono = "0.4"
bytes = "0.5"

serde = { version = "1", features = ["derive"] }
warp = "0.2"

tokio-postgres = "0.6"
bb8 = "0.6"
bb8-postgres = "0.6"

img_hash = "3"
image = "0.23"
hamming = "0.1"

bk-tree = "0.3"

[profile.dev]
opt-level = 2
debug = true

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
