[package]
name = "fa-watcher"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
reqwest = { git = "https://github.com/seanmonstar/reqwest" }
postgres = { version = "0.17.0-alpha.2", features = ["with-chrono-0_4"] }
tokio = { version = "0.2", features = ["macros", "time"] }
tokio-postgres = { version = "0.5.0-alpha.2" }
r2d2_postgres = " 0.16.0-alpha.2"
r2d2 = "0.8"
chrono = "0.4"

[dependencies.furaffinity-rs]
git = "https://git.huefox.com/syfaro/furaffinity-rs"
rev = "2477271b841335ee894cac18a74a338f9dc7262f"
