[workspace]
members = [
    "fuzzysearch",
    "fuzzysearch-common",
    "fuzzysearch-ingest-furaffinity",
    "fuzzysearch-ingest-weasyl"
]

[profile.dev]
opt-level = 2
debug = true

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
