[package]
name = "fuzzysearch-common"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
tracing = "0.1"

serde = { version = "1", features = ["derive"] }

image = "0.23"
img_hash = "3"

ffmpeg-next = "4"
tempfile = "3"
